export const SHORTCUTS = {
  global: [
    { label: "New Notebook", keys: "Alt + N" },
    { label: "Open File", keys: "Ctrl + O" },
    { label: "Save Notebook", keys: "Ctrl + S" },
    { label: "Save As", keys: "Ctrl + Shift + S" },
    { label: "Export .ipynb", keys: "Ctrl + E" },
    { label: "Toggle Shortcuts", keys: "Ctrl + \\" },
    { label: "Toggle Files & Data", keys: "Ctrl + ." },
    { label: "Presentation Mode", keys: "Alt + P" },
    { label: "Theme Configuration", keys: "Alt + T" },
    { label: "Code Visibility", keys: "Alt + V" },
    { label: "Run All Cells", keys: "Alt + R" },
    { label: "Clear All Outputs", keys: "Alt + Backspace" },
    { label: "Delete All Cells", keys: "Alt + Delete" },
    { label: "Restart Kernel", keys: "Alt + K" },
    { label: "Shutdown Kernel", keys: "Alt + Q" }
  ],
  command: [
    { label: "Run & Stay", keys: "Ctrl + Enter" },
    { label: "Run & Select Next", keys: "Shift + Enter" },
    { label: "Run & Insert", keys: "Alt + Enter" },
    { label: "Enter Edit Mode", keys: "Enter" },
    { label: "Deselect Cell", keys: "Esc" },
    { label: "Change to Code", keys: "Y" },
    { label: "Change to Markdown", keys: "M" },
    { label: "Move Up", keys: "Alt/Ctrl+Shift + ↑" },
    { label: "Move Down", keys: "Alt/Ctrl+Shift + ↓" },
    { label: "Insert Above", keys: "A" },
    { label: "Insert Below", keys: "B" },
    { label: "Delete Cell", keys: "Ctrl + Delete" },
    { label: "Clear Output", keys: "Ctrl + Backspace" }
  ],
  edit: [
    { label: "Run & Stay (Code)", keys: "Ctrl + Enter" },
    { label: "Render (Markdown)", keys: "Ctrl + Enter" },
    { label: "Run & Edit Next", keys: "Shift + Enter" },
    { label: "Run & Insert", keys: "Alt + Enter" },
    { label: "Exit Edit Mode", keys: "Esc" },
    { label: "Undo", keys: "Ctrl + Z" },
    { label: "Redo", keys: "Ctrl + Shift + Z" },
    { label: "Comment Toggle", keys: "Ctrl + /" },
    { label: "Multi-Select Next", keys: "Ctrl + D" },
    { label: "Multi-Select Previous", keys: "Ctrl + Shift + D" },
    { label: "Find", keys: "Ctrl + F" },
    { label: "Move Line Up", keys: "Ctrl + Shift + ↑" },
    { label: "Move Line Down", keys: "Ctrl + Shift + ↓" },
    { label: "Duplicate Line Up", keys: "Shift + Alt + ↑" },
    { label: "Duplicate Line Down", keys: "Shift + Alt + ↓" },
    { label: "Delete Line", keys: "Ctrl + Shift + K" },
    { label: "Jump to Bracket", keys: "Ctrl + M" },
    { label: "Clear Output", keys: "Ctrl + Backspace" }
  ]
};
